cloud_topic: /fastlio2/body_cloud
odom_topic: /fastlio2/lio_odom
map_frame: map
local_frame: odom

key_pose_delta_deg: 8.0
key_pose_delta_trans: 0.5
loop_search_radius: 5.0
loop_time_tresh: 45.0
loop_score_tresh: 0.15
loop_submap_half_range: 5
submap_resolution: 0.1
min_loop_detect_duration: 5.0
