octomap_server:
  ros__parameters:
    frame_id: odom
    base_frame_id: base_footprint
    resolution: 0.1
    height_map: true
    colored_map: true
    color_factor: 0.8
    filter_ground: true
    filter_speckles: true
    compress_map: true
    incremental_2D_projection: true
    publish_free_space: false
    sensor_model/hit: 0.74
    sensor_model/miss: 0.38
    sensor_model/min: 0.12
    sensor_model/max: 0.97
    pointcloud_min_z: -2.0
    pointcloud_max_z: 4.0
    pointcloud_min_x: -100.0
    pointcloud_max_x: 100.0
    pointcloud_min_y: -100.0
    pointcloud_max_y: 100.0
    occupancy_min_z: -1.0
    occupancy_max_z: 4.0
    min_x_size: 20.0
    min_y_size: 20.0
    ground_filter/distance: 0.05
    ground_filter/angle: 0.15
    ground_filter/plane_distance: 0.1
    sensor_model/max_range: -1.0
    color/r: 0.2
    color/g: 0.4
    color/b: 1.0
    color/a: 1.0
    color_free/r: 0.0
    color_free/g: 0.7
    color_free/b: 0.2
    color_free/a: 0.3
